# Config file for automatic testing at travis-ci.org

dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --editable .
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script: coverage run --source collections_extended setup.py test

after_success: coveralls
