name: Python package

on: [push, pull_request]

jobs:

  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install sphinx>=2.1 sphinxcontrib-napoleon
        pip install git+https://github.com/mlenzen/alabaster.git

    - name: Build Docs
      run: make docs

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run:
        pip install --upgrade pip
        pip install flake8 flake8-docstrings

    - name: Lint with flake8
      run: flake8 --statistics --count
    - name: Check for unfinished code
      run: make fixme-check

  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip coverage
        pip install pytest

    - name: Test with pytest
      run: coverage run --source collections_extended -m pytest
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: python-${{ matrix.python-version }}
        parallel: true

  coveralls:

    runs-on: ubuntu-latest

    needs: tests
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
